# - name: test var for join command
#   ansible.builtin.shell: kubeadm token create --print-join-command
#   register: join_command
#   when: "'k8s_main_master' in group_names"

# - name: print join command from cp1 vars
#   debug:
#     msg: "{{ hostvars[groups['k8s_main_master'][0]]['join_command']['stdout'] }}"
#   when: "'k8s_workers' in group_names"
