# - name: test var for join command
#   ansible.builtin.shell: kubeadm token create --print-join-command
#   register: join_command
#   when: "'k8s_main_master' in group_names"

# - name: print join command from cp1 vars
#   debug:
#     msg: "{{ hostvars[groups['k8s_main_master'][0]]['join_command']['stdout'] }}"
#   when: "'k8s_workers' in group_names"

# - name: print hostname
#   debug:
#     msg: "{{ hostvars[groups['k8s_main_master'][0]]['ansible_facts']['hostname'] }}"
#   delegate_to: k8s-cp-2

- name: Cat super-admin.conf in var
  ansible.builtin.shell: cat /etc/kubernetes/super-admin.conf
  register: super_admin
  delegate_to: "{{ hostvars[groups['k8s_main_master'][0]]['ansible_facts']['hostname'] }}"

- name: print super-admin.conf
  debug:
    msg: "{{ super_admin.stdout }}"

- name: "[BUG FIX] Copy super-admin.conf from main control plane"
  ansible.builtin.blockinfile:
    create: true
    path: /etc/kubernetes/super-admin.conf
    block: |
      {{ super_admin.stdout }}
  when:
    - kubevip_install
    - "'k8s_other_masters' in group_names"