---
- name: Get join command from main control plane
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ hostvars[groups['k8s_main_master'][0]]['ansible_facts']['hostname'] }}"
  changed_when: false

- name: Check if node has been initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join the cluster
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "{{ join_command.stdout }}"
  register: join_output
  when:
    - "'k8s_workers' in group_names"
    - not kubelet_conf.stat.exists
  changed_when: join_output.rc != 0
