- name: Initialize Kubernetes cluster
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      if [ ! -f /etc/kubernetes/admin.conf ]; then
        kubeadm init --pod-network-cidr={{ pod_network_cidr }}
      fi

- name: Create kube config directory for root user
  ansible.builtin.file:
    path: /root/.kube
    state: directory

- name: Ensure cluster access to root user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true

- name: Install CNI
  ansible.builtin.include_tasks:
    file: cni/{{ kubernetes_cni }}.yml

## Update CoreDNS conf if required

## Install kube-vip if required