---
- name: Get join command from main control plane
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command
  when: "'k8s_main_master' in group_names"

- name: Join the cluster
  ansible.builtin.shell: "{{ hostvars[groups['k8s_main_master'][0]]['join_command']['stdout'] }}"
  when: "'k8s_workers' in group_names"
