---
- name: tests
  ansible.builtin.include_tasks:
    file: debug.yml
    apply:
      tags: debug
  tags: debug
  when: "'k8s_main_master' in group_names"

- name: Prepare role execution
  ansible.builtin.include_tasks:
    file: prepare.yml
    apply:
      tags:
        - install
        - prepare
      any_errors_fatal: true
  tags:
    - install
    - prepare

- name: Install main k8s master
  ansible.builtin.include_tasks:
    file: install_main-master.yml
    apply:
      tags:
        - install
        - k8s
        - main_master
      any_errors_fatal: true
  tags:
    - install
    - k8s
    - main_master
  when: "'k8s_main_master' in group_names"

- name: Install other k8s master
  ansible.builtin.include_tasks:
    file: install_other_master.yml
    apply:
      tags:
        - install
        - k8s
        - other_master
      any_errors_fatal: true
  tags:
    - install
    - k8s
    - other_master
  when: ('k8s_main_master' in group_names) or
        ('k8s_other_masters' in group_names)

# - name: Install Helm on servers
#   ansible.builtin.include_tasks:
#     file: install_helm.yml
#     apply:
#       tags:
#         - install
#         - k8s
#         - helm
#       any_errors_fatal: true
#   tags:
#     - install
#     - k8s
#     - helm
#   when: ('k8s_main_server' in group_names and helm_install) or
#         ('k8s_other_servers' in group_names and helm_install)

- name: Install k8s workers
  ansible.builtin.include_tasks:
    file: install_worker.yml
    apply:
      tags:
        - install
        - k8s
        - worker
      any_errors_fatal: true
  tags:
    - install
    - k8s
    - worker
  when: ('k8s_main_master' in group_names) or
        ('k8s_workers' in group_names)

# - name: Uninstall k8s
#   ansible.builtin.include_tasks: uninstall.yml
#   tags:
#     - uninstall
