---
- name: Prepare role execution
  ansible.builtin.include_tasks:
    file: prepare.yml
    apply:
      tags:
        - install
        - prepare
      any_errors_fatal: true
  tags:
    - install
    - prepare

- name: Install main k8s master
  ansible.builtin.include_tasks:
    file: install_main-master.yml
    apply:
      tags:
        - install
        - k8s
        - main_master
      any_errors_fatal: true
  tags:
    - install
    - k8s
    - main_master
  when: "'k8s_main_master' in group_names"

- name: Install other k8s master
  ansible.builtin.include_tasks:
    file: install_other-master.yml
    apply:
      tags:
        - install
        - k8s
        - other_master
      any_errors_fatal: true
  tags:
    - install
    - k8s
    - other_master
  when: "'k8s_other_masters' in group_names"

- name: Install k8s workers
  ansible.builtin.include_tasks:
    file: install_worker.yml
    apply:
      tags:
        - install
        - k8s
        - worker
      any_errors_fatal: true
  tags:
    - install
    - k8s
    - worker
  when: "'k8s_workers' in group_names"
