---
- name: Check if vip_address is set
  ansible.builtin.assert:
    that:
      - vip_address is defined
    fail_msg: "vip_address variable is not defined"
    quiet: true
  when: kubevip_install

- name: Check if nfs_server_address is set
  ansible.builtin.assert:
    that:
      - nfs_server_address is defined
    fail_msg: "nfs_server_address variable is not defined"
    quiet: true
  when: kubernetes_storageclass == 'nfs'

- name: Check if nfs_server_path is set
  ansible.builtin.assert:
    that:
      - nfs_server_path is defined
    fail_msg: "nfs_server_path variable is not defined"
    quiet: true
  when: kubernetes_storageclass == 'nfs'

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Set hosts hostnames
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: "{{ item.strategy }}"
  when:
    - item.test
    - set_hostnames
  loop:
    - test: ansible_os_family == "RedHat"
      strategy: systemd
    - test: ansible_os_family == "Debian"
      strategy: debian

- name: Set /etc/hosts to reflect hostnames
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }}\t{{ item }}"
  loop: "{{ groups.all }}"

- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Disable swap in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    enabled: false
    state: stopped
  when:
    - ansible_os_family == "RedHat"
    - ansible_facts.services['firewalld'] is defined

- name: Set SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"

- name: Activate overlay and br_netfilter kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - overlay
    - br_netfilter

- name: Add sysctls for kubelet
  ansible.posix.sysctl:
    name: "{{ item.sysctl }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - sysctl: net.ipv4.ip_forward
      value: 1
    - sysctl: net.bridge.bridge-nf-call-iptables
      value: 1
    - sysctl: net.bridge.bridge-nf-call-ip6tables
      value: 1
    - sysctl: vm.overcommit_memory
      value: 1
    - sysctl: kernel.panic
      value: 10
    - sysctl: kernel.panic_on_oops
      value: 1

- name: Disable nm-cloud-setup service if applicable
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - nm-cloud-setup.service
    - nm-cloud-setup.timer
  when:
    - ansible_facts.services['nm-cloud-setup'] is defined

- name: Update repository cache
  ansible.builtin.apt:
    update_cache: true
  when:
    - ansible_os_family == "Debian"

- name: Install dependencies
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - python3-pip
      - jq
      - git
      - openssl
      - gpg
    state: present

- name: Install iproute-tc
  ansible.builtin.package:
    name: iproute-tc
    state: present
  when: ansible_os_family == "RedHat"

- name: Install iproute2
  ansible.builtin.package:
    name: iproute2
    state: present
  when: ansible_os_family == "Debian"

- name: Install nfs-common
  ansible.builtin.package:
    name: nfs-common
    state: present
  when:
    - ansible_os_family == "Debian"
    - kubernetes_storageclass == "nfs"

- name: Install Kubernetes Python module
  ansible.builtin.pip:
    name: kubernetes
  when: ansible_os_family == "RedHat"

- name: Install Kubernetes Python module system-wide
  ansible.builtin.package:
    name: python3-kubernetes
    state: present
  when: ansible_os_family == "Debian"

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: '0755'
    state: directory
  when:
    - ansible_os_family == "Debian"

- name: Get Docker repository GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '644'
  when:
    - ansible_os_family == "Debian"

- name: Set read permissions on docker.asc
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: u+r,g+r,o+r
  when:
    - ansible_os_family == "Debian"

- name: Add Docker repository
  block:
    - name: Add docker repository (Debian)
      ansible.builtin.apt_repository:
        filename: docker-ce
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
      when:
        - ansible_os_family == "Debian"
    - name: Add docker repository (RHEL)
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '644'
      when:
        - ansible_os_family == "RedHat"

- name: Check if Kubernetes repository GPG key exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: stat_result
  when: ansible_os_family == "Debian"

- name: Get Kubernetes repository GPG key
  ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when:
    - ansible_os_family == "Debian"
    - not stat_result.stat.exists

- name: Add Kubernetes repository
  block:
    - name: Add k8s.io repository (Debian)
      ansible.builtin.apt_repository:
        filename: kubernetes
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /"
        state: present
      when:
        - ansible_os_family == "Debian"
    - name: Add k8s.io repository (RHEL)
      ansible.builtin.yum_repository:
        name: kubernetes
        description: k8s.io repository
        baseurl: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/
        gpgcheck: true
        gpgkey: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/repodata/repomd.xml.key
      when:
        - ansible_os_family == "RedHat"

- name: Update repository cache
  ansible.builtin.apt:
    update_cache: true
  when:
    - ansible_os_family == "Debian"

- name: Install containerd.io
  ansible.builtin.package:
    name: containerd.io
    state: present

- name: Create default config for containerd
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  register: containerd_output
  changed_when: containerd_output.rc != 0

- name: Enable systemd Cgroup for containerd
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Enable and start containerd unit
  ansible.builtin.service:
    name: containerd
    enabled: true
    state: restarted

- name: Install kubeadm and kubelet packages on all nodes
  ansible.builtin.package:
    name:
      - kubeadm
      - kubelet
    state: present

- name: Install kubectl package on master nodes
  ansible.builtin.package:
    name: kubectl
    state: present
  when: ('k8s_main_master' in group_names) or
        ('k8s_other_masters' in group_names)

- name: Install Helm on master nodes
  ansible.builtin.shell: set -o pipefail && PATH=/usr/local/bin:$PATH && curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  register: helm_output
  when: ('k8s_main_master' in group_names) or
        ('k8s_other_masters' in group_names)
  changed_when: helm_output.rc != 0

- name: Enable kubelet unit
  ansible.builtin.service:
    name: kubelet
    enabled: true

- name: Exclude Kubernetes components from updates
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: exclude = kubeadm kubelet kubectl
  when: ansible_os_family == "RedHat"

- name: Prevent kubeadm and kubelet from being upgraded
  ansible.builtin.shell: |
      sudo apt-mark hold kubeadm
      sudo apt-mark hold kubelet
  register: hold_output
  when: ansible_os_family == "Debian"
  changed_when: hold_output.rc != 0

- name: Prevent kubectl from being upgraded
  ansible.builtin.shell: |
      sudo apt-mark hold kubectl
  register: hold_output
  when:
    - ansible_os_family == "Debian"
    - ('k8s_main_master' in group_names) or
      ('k8s_other_masters' in group_names)
  changed_when: hold_output.rc != 0
