---
- name: Add NFS Subdir External Provisionner Helm repository
  kubernetes.core.helm_repository:
    binary_path: /usr/local/bin/helm
    name: nfs-subdir-external-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

- name: Install NFS Subdir External Provisionner
  kubernetes.core.helm:
    binary_path: /usr/local/bin/helm
    name: nfs-subdir-external-provisioner
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: kube-system
    values:
      nfs:
        server: "{{ nfs_server_address }}"
        path: "{{ nfs_server_path }}"
        volumeName: nfs-subdir-external-provisioner-root
      storageClass:
        defaultClass: true
